Repository Gizra/og, pull requests merged in 2018-06, with the labels that each got.

#380 hook_og_permission() does not document its @return
  og.api.php
Labels: Documentation, Drupal 7

#382 @return docs for og_get_entity_groups() unclear
  og.module
Labels: Documentation, Drupal 7

#126 Fixed #125: Behavior for og_membership_delete_action
  includes/actions/membership_delete.action.inc
Labels: Bug, Drupal 7

#185 Fixed: og_help function in og.module refers now README.md.
  og.module
Labels: Documentation, Drupal 7

#384 og_is_member() documentation incorrectly inform about $states parameter
  og.module
Labels: Documentation, Drupal 7

#359 Fixes #152: Replaces NULL returns with emtpy array returns in og_get_groups_by_user()
  .travis.yml
  og.module
  plugins/entityreference/selection/OgSelectionHandler.class.php
Labels: Bug, Drupal 7

#386 Unsubscribe confirm firm uses 'Remove' as button text
  og_ui/og_ui.pages.inc
  og_ui/og_ui.test
Labels: Clean-up, Drupal 7

#387 og_form_group_manager_validate() assumes the entity form has a language
  og.module
Labels: Bug, Drupal 7

#388 OG subscribe / join page not working with field permissions on group field
  og_ui/og_ui.pages.inc
Labels: Bug, Drupal 7

#320 og_ui edit_membership_form disable checkboxes if member is not active.
  og_ui/og_ui.admin.inc
Labels: Bug, Drupal 7

#276 Remove duplicate checks in og_ui_user_access_group
  og_ui/og_ui.module
Labels: Bug, Clean-up, Drupal 7

#389 Use correct class name in exception message
  src/MembershipManager.php
Labels: Bug, Drupal 8, Ready for review

#322 Group owner membership is activated on every group save
  og.module
  og.test
Labels: Bug, Drupal 7

#353 Undefined property stdClass::$original in og_entity_update when updating group
  og.module
Labels: Bug, Drupal 7

#390 OG 7.x 2.10 release
  og.api.php
  og.info
  og.module
  og.test
  og_access/og_access.info
  og_context/og_context.info
  og_field_access/og_field_access.info
  og_register/og_register.info
  og_ui/og_ui.admin.inc
  og_ui/og_ui.module
  og_ui/og_ui.pages.inc
  og_ui/og_ui.test
  plugins/entityreference/behavior/OgBehaviorHandler.class.php
  plugins/entityreference/selection/OgSelectionHandler.class.php
Labels: Drupal 7, Needs QA
