Repository Gizra/og, pull requests merged in 2018-07, with the labels that each got.

#395 Test on current versions of Drupal and PHP.
  .travis.yml
  composer.json
  scripts/travis-ci/run-test.sh
  src/Form/GroupSubscribeForm.php
  src/Form/OgChangeMultipleRolesFormBase.php
  src/Plugin/Action/ChangeMultipleOgMembershipRolesBase.php
  tests/src/Functional/GroupSubscribeFormatterTest.php
  tests/src/Functional/GroupSubscribeTest.php
  tests/src/Functional/GroupTabTest.php
  tests/src/Functional/OgComplexWidgetTest.php
  tests/src/Kernel/Access/OgEntityAccessTest.php
  tests/src/Kernel/Access/OgGroupContentOperationAccessTest.php
  tests/src/Kernel/Action/ActionTestBase.php
  tests/src/Kernel/Action/ChangeMultipleOgMembershipRolesActionTestBase.php
  tests/src/Kernel/Entity/FieldCreateTest.php
  tests/src/Kernel/Entity/GetGroupContentTest.php
  tests/src/Kernel/Entity/GetUserGroupsTest.php
  tests/src/Kernel/Entity/GroupAudienceTest.php
  tests/src/Kernel/Entity/GroupMembershipManagerTest.php
  tests/src/Kernel/Entity/OgMembershipRoleReferenceTest.php
  tests/src/Kernel/Entity/OgMembershipTest.php
  tests/src/Kernel/Entity/OgStandardReferenceItemTest.php
  tests/src/Kernel/Entity/ReferenceStringIdTest.php
  tests/src/Kernel/Entity/SelectionHandlerTest.php
  tests/src/Kernel/Form/GroupSubscribeFormTest.php
  tests/src/Kernel/OgDeleteOrphansTest.php
  tests/src/Kernel/OgRoleManagerTest.php
  tests/src/Kernel/PermissionEventTest.php
  tests/src/Kernel/Views/OgAdminMembersViewTest.php
  tests/src/Unit/CreateMembershipTest.php
  tests/src/Unit/GroupSubscribeFormatterTest.php
Labels: Drupal 8, Ready for review

#374 Adds new access check to `og_entity_access`
  og.module
  tests/src/Kernel/Access/OgAccessHookTest.php
  tests/src/Unit/OgAccessTestBase.php
Labels: Bug, Drupal 8

#404 Rename getGroupsForEntityType into getGroupBundleIdsByEntityType
  src/GroupTypeManager.php
  src/GroupTypeManagerInterface.php
  tests/src/Unit/GroupTypeManagerTest.php
Labels: Clean-up, Drupal 8

#394 Provide a trait for creating memberships in tests
  tests/src/Functional/GroupSubscribeTest.php
  tests/src/Functional/GroupUpdateTest.php
  tests/src/Kernel/Access/AccessByOgMembershipTest.php
  tests/src/Kernel/Access/OgAccessHookTest.php
  tests/src/Kernel/Access/OgGroupContentOperationAccessTest.php
  tests/src/Kernel/Action/ActionTestBase.php
  tests/src/Kernel/Entity/GetMembershipsTest.php
  tests/src/Kernel/Entity/GetUserGroupsTest.php
  tests/src/Traits/OgMembershipCreationTrait.php
Labels: Clean-up, Drupal 8, Ready for review

#408 We can update the generic @return array type hints to more precise da…
  src/GroupTypeManagerInterface.php
Labels: Clean-up, Drupal 8
