Repository Gizra/og, pull requests merged in 2019-08, with the labels that each got.

#561 Create a test for OgMembershipInterface::getRolesIds()
  tests/src/Kernel/Entity/OgMembershipTest.php
Labels: Drupal 8

#529 Consolidate the permissions regarding roles and permissions.
  src/EventSubscriber/OgEventSubscriber.php
  tests/src/Kernel/PermissionEventTest.php
Labels: Clean-up, Drupal 8, Ready for review

#555 Improve performance of working with large numbers of memberships
  src/Cache/Context/OgRoleCacheContext.php
  src/Entity/OgMembership.php
  tests/src/Unit/Cache/Context/OgRoleCacheContextTest.php
Labels: Drupal 8, Performance

#559 Speed up retrieval of membership data by using a SELECT query
  og.services.yml
  src/Cache/Context/OgRoleCacheContext.php
  tests/src/Kernel/Cache/Context/OgRoleCacheContextTest.php
  tests/src/Traits/OgRoleCacheContextTestTrait.php
  tests/src/Unit/Cache/Context/OgRoleCacheContextTest.php
Labels: Drupal 8, Performance

#564 254 Default argument membership
  src/Plugin/views/argument_default/Membership.php
Labels: Drupal 8, Feature request

#563 Upgrade to xenial
  .travis.yml
Labels: Ready for review
