Repository Gizra/og, pull requests merged in 2019-05, with the labels that each got.

#486 472 Fixes
  og.module
  src/Plugin/Block/MemberCountBlock.php
  templates/og-member-count.html.twig
  tests/src/Kernel/Plugin/Block/MemberCountBlockTest.php
Labels: Clean-up, Drupal 8, Ready for review

#489 Declare PHP 7.1 as the minimum supported version
  composer.json
  og.info.yml
Labels: Documentation, Drupal 8

#492 Add slack to support channels
  composer.json
Labels: Documentation, Ready for review

#484 Optimize performance of og_get_all_group_entity()
  og.module
Labels: Drupal 7, Performance

#311 Throw an exception when calling `MembershipManager::getGroupIds()` with an entity which is not group content
  src/MembershipManager.php
  src/OgAccess.php
  src/OgDeleteOrphansBase.php
  tests/src/Kernel/Entity/GroupMembershipManagerTest.php
Labels: Bug, Drupal 8, Ready for review

#496 Fix namespaces
  og.info.yml
  tests/modules/og_standard_reference_test_views/og_standard_reference_test_views.info.yml
  tests/modules/og_test/og_test.info.yml
Labels: Clean-up, Drupal 8, Ready for review

#495 Improve the checks if an entity is a user
  src/MembershipManager.php
  src/OgAccess.php
  src/Plugin/Field/FieldWidget/OgComplex.php
  src/Plugin/OgFields/AudienceField.php
Labels: Clean-up, Drupal 8, Ready for review

#493 Use strict types in the OgMembership entity
  og.module
  src/Entity/OgMembership.php
  src/OgMembershipInterface.php
  tests/src/Kernel/Entity/OgMembershipTest.php
  tests/src/Unit/CreateMembershipTest.php
Labels: Drupal 8, Feature request

#503 Fix random failure in OgMembershipTest::testGetSetCreatedTime().
  tests/src/Kernel/Entity/OgMembershipTest.php
Labels: Bug, Drupal 8, Ready for review

#498 Fixed documentation
  src/MembershipManagerInterface.php
  src/Og.php
Labels: Documentation, Drupal 8, Ready for review

#482 Groups and roles by permissions
  src/MembershipManager.php
  src/MembershipManagerInterface.php
  src/OgRoleManager.php
  src/OgRoleManagerInterface.php
  tests/src/Kernel/Entity/GetUserGroupsTest.php
  tests/src/Kernel/OgRoleManagerTest.php
  tests/src/Unit/OgRoleManagerTest.php
Labels: Drupal 8, Feature request

#509 Do not invalidate group content list cache tags when the group itself changes
  og.module
  tests/src/Kernel/Entity/CacheInvalidationOnGroupChangeTest.php
Labels: Bug, Drupal 8, Ready for review
