Repository Gizra/og, pull requests merged in 2019-06, with the labels that each got.

#514 Fixed codesniffer errors
  src/Access/GroupCheck.php
  tests/src/Kernel/PermissionEventTest.php
Labels: Clean-up, Drupal 8, Ready for review

#516 Do not require to pass full OgRole objects when we only need the ID.
  src/MembershipManager.php
  src/MembershipManagerInterface.php
  tests/src/Kernel/Entity/GetUserGroupsTest.php
Labels: Clean-up, Drupal 8, Performance

#524 Code example to add a group content type is not valid PHP
  README.md
Labels: Bug, Documentation, Drupal 8, Ready for review

#523 Uncaught Error: Cannot use object of type stdClass as array
  src/GroupTypeManager.php
  tests/src/Kernel/Entity/GetBundleByBundleTest.php
Labels: Bug, Drupal 8, Ready for review

#499 Test that an exception is thrown when a membership is saved using invalid roles
  tests/src/Kernel/Entity/OgMembershipTest.php
Labels: Drupal 8, Ready for review

#533 Fixed missing member variable doc comment
  src/Entity/OgMembershipType.php
  tests/src/Kernel/Entity/OgStandardReferenceItemTest.php
Labels: Clean-up, Drupal 8, Ready for review
