Repository Gizra/og, pull requests merged in 2019-04, with the labels that each got.

#467 Use full pager on member overview
  config/optional/views.view.og_members_overview.yml
  tests/src/Kernel/Views/OgAdminMembersViewTest.php
Labels: Drupal 8, Feature request, Ready for review

#465 Fix broken/missing handler for roles in og membership view
  config/optional/views.view.og_members_overview.yml
Labels: Bug, Drupal 8, Ready for review

#473 Add support for Drupal 8.7.x
  .travis.yml
  composer.json
  src/Entity/OgMembershipType.php
  src/Plugin/Condition/GroupType.php
  tests/src/Functional/OgComplexWidgetTest.php
  tests/src/Kernel/Access/OgGroupContentOperationAccessTest.php
  tests/src/Kernel/Action/ActionTestBase.php
  tests/src/Kernel/Entity/EntityCreateAccessTest.php
  tests/src/Kernel/GroupManagerSubscriptionTest.php
  tests/src/Kernel/GroupTypeConditionTest.php
  tests/src/Kernel/OgDeleteOrphansTest.php
  tests/src/Kernel/Views/OgAdminMembersViewTest.php
Labels: Clean-up, Drupal 8, Ready for review

#450 Use cache api to store the group relation map
  og.services.yml
  src/GroupTypeManager.php
  tests/src/Unit/GroupTypeManagerTest.php
Labels: Clean-up, Drupal 8, Ready for review

#471 Unnecessarily gendered language in a comment
  tests/src/Kernel/Entity/SelectionHandlerTest.php
Labels: Clean-up, Drupal 8, Ready for review

#461 Fix minor typo in subscribe form
  src/Form/GroupSubscribeForm.php
Labels: Drupal 8

#476 Only allow users with `access user profiles` permission to access the members overview
  config/optional/views.view.og_members_overview.yml
Labels: Drupal 8, Feature request, Ready for review

#478 433 Remove deprecated setting for use_queue
  og_ui/src/Form/AdminSettingsForm.php
Labels: Clean-up, Drupal 8, Ready for review

#475 Provide a method to retrieve the membership IDs of a given group
  src/MembershipManager.php
  src/MembershipManagerInterface.php
  tests/src/Kernel/Entity/GroupMembershipManagerTest.php
Labels: Drupal 8

#443 Fix config import of og role actions
  og.module
Labels: Bug, Drupal 8, Ready for review

#479 MembershipManager returns memberships of the wrong group
  src/MembershipManager.php
  tests/src/Kernel/Entity/GroupMembershipManagerTest.php
Labels: Bug, Drupal 8, Ready for review

#480 MembershipManager still returns a user's memberships after the user is deleted
  og.module
  og.services.yml
  src/Entity/OgMembership.php
  src/MembershipManager.php
  src/MembershipManagerInterface.php
  src/Og.php
  tests/src/Kernel/Entity/CacheInvalidationOnGroupChangeTest.php
  tests/src/Kernel/Entity/GroupMembershipManagerTest.php
  tests/src/Unit/CreateMembershipTest.php
Labels: Bug, Drupal 8, Ready for review
