Repository Gizra/og, pull requests merged in 2020-08, with the labels that each got.

#673 Split up OgAccess::userAccessEntity()
  og.module
  og.services.yml
  src/EventSubscriber/OgEventSubscriber.php
  src/Og.php
  src/OgAccess.php
  src/OgAccessInterface.php
  tests/src/Kernel/Access/OgGroupContentOperationAccessTest.php
  tests/src/Unit/OgAccessEntityTest.php
  tests/src/Unit/OgAccessEntityTestBase.php
  tests/src/Unit/OgAccessTestBase.php
Labels: Clean-up, Drupal 8, Ready for review

#681 Provide "delete" entity operation access check on group entities
  src/EventSubscriber/OgEventSubscriber.php
  src/OgAccess.php
  src/PermissionManagerInterface.php
  tests/src/Kernel/Access/GroupLevelAccessTest.php
  tests/src/Kernel/Access/OgEntityAccessTest.php
  tests/src/Kernel/PermissionEventTest.php
Labels: Drupal 8, Feature request, Ready for review

#685 Cleanup OgMembership::preSave
  src/Entity/OgMembership.php
Labels: Clean-up, Drupal 8, Ready for review

#690 Fix deprecated license
  composer.json
Labels: Drupal 8, Ready for review

#689 Extend OgRoleInterface from RoleInterface
  og.module
  src/Event/DefaultRoleEventInterface.php
  src/OgRoleInterface.php
  tests/src/Kernel/Access/OgGroupContentOperationAccessTest.php
Labels: Clean-up, Drupal 8, Ready for review

#402 Remove getAllGroupBundles and replace with getGroupMap
  og_ui/src/BundleFormAlter.php
  og_ui/src/Controller/OgUiController.php
  src/GroupTypeManager.php
  src/GroupTypeManagerInterface.php
  src/Plugin/Condition/GroupType.php
  src/Plugin/EntityReferenceSelection/OgSelection.php
  tests/src/Unit/GroupTypeManagerTest.php
Labels: Clean-up, Drupal 8, Ready for review

#684 Group content entity operations ~~hook~~ event
  og.api.php
  og.services.yml
  src/Event/AccessEventBase.php
  src/Event/AccessEventInterface.php
  src/Event/GroupContentEntityOperationAccessEvent.php
  src/Event/GroupContentEntityOperationAccessEventInterface.php
  src/EventSubscriber/OgEventSubscriber.php
  src/OgAccess.php
  tests/modules/og_test/og_test.install
  tests/modules/og_test/og_test.module
  tests/modules/og_test/og_test.permissions.yml
  tests/modules/og_test/og_test.services.yml
  tests/modules/og_test/src/EventSubscriber/OgTestEventSubscriber.php
  tests/src/Kernel/Access/GroupContentOperationAccessAlterTest.php
  tests/src/Unit/OgAccessTestBase.php
Labels: Drupal 8, Feature request, Ready for review

#697 Document why we are doing an interface check
  src/Event/AccessEventBase.php
Labels: Drupal 8

#695 694 Fix access condition check in SubscriptionController
  src/Controller/SubscriptionController.php
  tests/src/Functional/GroupSubscribeTest.php
Labels: Bug, Drupal 8
