Repository Gizra/og, pull requests merged in 2020-02, with the labels that each got.

#610 Fix for #580.
  og.module
  src/Og.php
  tests/src/Kernel/Entity/SelectionHandlerTest.php
Labels: Clean-up, Drupal 8

#612 550 Remove global constants
  og.module
  phpcs-ruleset.xml.dist
  src/Plugin/OgFields/AccessField.php
  tests/src/Kernel/Entity/FieldCreateTest.php
Labels: Clean-up, Drupal 8, Ready for review

#616 615 Upgrade to Xenial
  .travis.yml
Labels: Drupal 7, Ready for review

#601 `User::load()` calls should be avoided in classes #546 fix
  phpcs-ruleset.xml.dist
  src/Controller/SubscriptionController.php
  src/Plugin/Field/FieldFormatter/GroupSubscribeFormatter.php
  tests/src/Unit/GroupSubscribeFormatterTest.php
  tests/src/Unit/SubscriptionControllerTest.php
Labels: Clean-up, Drupal 8, Ready for review

#619 Remove deprecated sudo property
  .travis.yml
Labels: Clean-up, Drupal 8, Ready for review

#622 Use selectionPluginManager::getInstance() to get default selection handler
  og.module
  tests/src/Kernel/Entity/SelectionHandlerTest.php
Labels: Drupal 8, Ready for review

#621 544 Namespace all dependencies
  phpcs-ruleset.xml.dist
Labels: Clean-up, Drupal 8, Ready for review

#594 549 Check for undefined variables
  phpcs-ruleset.xml.dist
  tests/src/Kernel/Action/ApprovePendingOgMembershipActionTest.php
  tests/src/Kernel/Action/ChangeMultipleOgMembershipRolesActionTestBase.php
  tests/src/Kernel/Action/DeleteOgMembershipActionTest.php
  tests/src/Kernel/Action/PendingOgMembershipActionTest.php
  tests/src/Kernel/Action/UnblockOgMembershipActionTest.php
Labels: Clean-up, Drupal 8, Ready for review

#618 617 Remove unused access_override setting
  config/schema/og.schema.yml
  src/Plugin/Field/FieldType/OgStandardReferenceItem.php
Labels: Clean-up, Drupal 8, Ready for review

#629 Use custom phpcs configuration
  .codeclimate.yml
Labels: Clean-up

#513 Add OgAccessInterface::userAccessGroupContentEntityOperation
  src/OgAccess.php
  src/OgAccessInterface.php
Labels: Clean-up, Documentation, Drupal 8, Ready for review
