Repository Gizra/og, pull requests merged in 2020-07, with the labels that each got.

#649 Drop support for Drupal 8.7.x
  .travis.yml
  composer.json
  og.info.yml
Labels: Clean-up, Drupal 8, Ready for review

#650 Add support for Drupal 9.1
  .travis.yml
  og_ui/tests/src/Functional/BundleFormAlterTest.php
  tests/src/Functional/GroupSubscribeFormatterTest.php
  tests/src/Functional/GroupSubscribeTest.php
  tests/src/Functional/GroupTabTest.php
  tests/src/Functional/GroupUpdateTest.php
  tests/src/Functional/OgComplexWidgetTest.php
  tests/src/Kernel/Access/AccessByOgMembershipTest.php
  tests/src/Kernel/Access/OgAccessHookTest.php
  tests/src/Kernel/Access/OgEntityAccessTest.php
  tests/src/Kernel/Access/OgGroupContentOperationAccessTest.php
  tests/src/Kernel/Action/ActionTestBase.php
  tests/src/Kernel/Action/ChangeMultipleOgMembershipRolesActionTestBase.php
  tests/src/Kernel/Cache/Context/OgRoleCacheContextTest.php
  tests/src/Kernel/DefaultRoleEventIntegrationTest.php
  tests/src/Kernel/Entity/CacheInvalidationOnGroupChangeTest.php
  tests/src/Kernel/Entity/EntityCreateAccessTest.php
  tests/src/Kernel/Entity/FieldCreateTest.php
  tests/src/Kernel/Entity/GetBundleByBundleTest.php
  tests/src/Kernel/Entity/GetGroupContentTest.php
  tests/src/Kernel/Entity/GetMembershipsTest.php
  tests/src/Kernel/Entity/GetUserGroupsTest.php
  tests/src/Kernel/Entity/GroupAudienceTest.php
  tests/src/Kernel/Entity/GroupMembershipManagerTest.php
  tests/src/Kernel/Entity/GroupTypeTest.php
  tests/src/Kernel/Entity/OgMembershipRoleReferenceTest.php
  tests/src/Kernel/Entity/OgMembershipTest.php
  tests/src/Kernel/Entity/OgRoleTest.php
  tests/src/Kernel/Entity/OgStandardReferenceItemTest.php
  tests/src/Kernel/Entity/ReferenceStringIdTest.php
  tests/src/Kernel/Entity/SelectionHandlerTest.php
  tests/src/Kernel/EntityReference/Views/OgStandardReferenceRelationshipTest.php
  tests/src/Kernel/Form/GroupSubscribeFormTest.php
  tests/src/Kernel/GroupManagerSubscriptionTest.php
  tests/src/Kernel/GroupTypeConditionTest.php
  tests/src/Kernel/OgDeleteOrphansTest.php
  tests/src/Kernel/OgRoleManagerTest.php
  tests/src/Kernel/PermissionEventTest.php
  tests/src/Kernel/Plugin/Block/MemberCountBlockTest.php
  tests/src/Unit/Cache/Context/OgContextCacheContextTestBase.php
  tests/src/Unit/Cache/Context/OgMembershipStateCacheContextTest.php
  tests/src/Unit/Cache/Context/OgRoleCacheContextTest.php
  tests/src/Unit/CreateMembershipTest.php
  tests/src/Unit/DefaultRoleEventTest.php
  tests/src/Unit/GroupCheckTest.php
  tests/src/Unit/GroupSubscribeFormatterTest.php
  tests/src/Unit/GroupTypeManagerTest.php
  tests/src/Unit/OgAccessEntityTestBase.php
  tests/src/Unit/OgAccessHookTest.php
  tests/src/Unit/OgAccessTestBase.php
  tests/src/Unit/OgAdminRoutesControllerTest.php
  tests/src/Unit/OgContextTest.php
  tests/src/Unit/OgLocalTaskTest.php
  tests/src/Unit/OgResolvedGroupCollectionTest.php
  tests/src/Unit/OgRoleManagerTest.php
  tests/src/Unit/Plugin/OgGroupResolver/OgGroupResolverTestBase.php
  tests/src/Unit/Plugin/OgGroupResolver/OgRouteGroupResolverTestBase.php
  tests/src/Unit/Plugin/OgGroupResolver/RequestQueryArgumentResolverTest.php
  tests/src/Unit/SubscriptionControllerTest.php
Labels: Bug, Drupal 9

#648 Remove dead code in OgAccessHookTest
  tests/src/Unit/OgAccessHookTest.php
Labels: Clean-up, Drupal 8, Ready for review

#614 543 Remove `t()` calls
  og.install
  og.module
  og.views.inc
  og_ui/src/BundleFormAlter.php
  og_ui/src/Controller/OgUiController.php
  og_ui/tests/src/Functional/BundleFormAlterTest.php
  phpcs-ruleset.xml.dist
  src/Cache/Context/OgGroupContextCacheContext.php
  src/Cache/Context/OgMembershipStateCacheContext.php
  src/Cache/Context/OgRoleCacheContext.php
  src/Entity/OgMembership.php
  src/EventSubscriber/OgEventSubscriber.php
  src/Form/OgAddMultipleRolesForm.php
  src/Form/OgChangeMultipleRolesFormBase.php
  src/Form/OgRemoveMultipleRolesForm.php
  src/Plugin/Action/ChangeSingleOgMembershipRoleBase.php
  src/Plugin/Field/FieldWidget/OgComplex.php
Labels: Clean-up, Drupal 8, Novice, Ready for review

#655 Remove the static cache in OgAccess::userAccess().
  phpcs-ruleset.xml.dist
  src/Entity/OgMembership.php
  src/Entity/OgRole.php
  src/OgAccess.php
  src/OgAccessInterface.php
Labels: Clean-up, Drupal 8

#653 Remove the 'ignore_admin' flag.
  src/OgAccess.php
  src/OgAccessInterface.php
Labels: Clean-up, Drupal 8

#662 Drupal 9.1.x deprecation notice: AssertLegacyTrait::assertOptionSelected() is deprecated
  og_ui/tests/src/Functional/BundleFormAlterTest.php
Labels: Clean-up, Drupal 9

#664 Do not check for deprecated code on D9
  composer.json
  scripts/travis-ci/run-test.sh
Labels: Clean-up, Drupal 9, Ready for review

#656 Travis integration - switch to Bionic
  .travis.yml
Labels: Ready for review

#665 Drop support for php 7.1
  composer.json
Labels: Clean-up

#661 Rename the global permission to administer all groups to 'administer organic groups'
  og.module
  og.permissions.yml
  og_ui/og_ui.routing.yml
  src/Access/GroupCheck.php
  src/Event/OgAdminRoutesEvent.php
  src/EventSubscriber/OgEventSubscriber.php
  src/OgAccess.php
  src/Plugin/Field/FieldWidget/OgComplex.php
  src/Routing/RouteSubscriber.php
  tests/src/Functional/GroupTabTest.php
  tests/src/Functional/OgComplexWidgetTest.php
  tests/src/Kernel/Access/OgAccessHookTest.php
  tests/src/Kernel/Action/ActionTestBase.php
  tests/src/Kernel/Entity/OgMembershipRoleReferenceTest.php
  tests/src/Kernel/Entity/OgRoleTest.php
  tests/src/Kernel/OgRoleManagerTest.php
  tests/src/Kernel/PermissionEventTest.php
  tests/src/Unit/OgAccessEntityTest.php
  tests/src/Unit/OgAccessHookTest.php
  tests/src/Unit/OgAccessTest.php
  tests/src/Unit/OgAccessTestBase.php
  tests/src/Unit/PermissionEventTest.php
Labels: Clean-up, Drupal 8

#666 Fixed grammar
  src/OgAccess.php
Labels: Clean-up, Documentation, Ready for review

#668 667 Use PHPUnit 7 for testing
  .travis.yml
Labels: Ready for review

#670 Remove obsolete service definition
  og.services.yml
Labels: Clean-up, Drupal 8

#671 User access check should no longer accept operations, only permissions
  src/OgAccess.php
  src/OgAccessInterface.php
  tests/src/Functional/GroupUpdateTest.php
  tests/src/Kernel/Access/OgEntityAccessTest.php
Labels: Clean-up, Drupal 8, Ready for review

#677 Add support for php 7.4
  .travis.yml
Labels: Drupal 8
