Repository Gizra/og, pull requests merged in 2021-07, with the labels that each got.

#722 Deprecate php 7.2 and drupal 8.8
  .travis.yml
Labels: CI, Clean-up, Drupal 8, Drupal 9, Ready for review

#724 Remove config hash
  config/optional/views.view.og_members_overview.yml
Labels: Clean-up, Ready for review

#704 Remove any null values when building the list of target groups.
  src/MembershipManager.php
Labels: Drupal 8, Ready for review

#723 Add support for Drupal 9.2
  .travis.yml
Labels: Ready for review
