Repository Gizra/og, pull requests merged in 2021-01, with the labels that each got.

#700 Fix PHP CS issues
  og.views.inc
  og_ui/src/Form/AdminSettingsForm.php
  og_ui/tests/src/Functional/BundleFormAlterTest.php
  src/Controller/OgAdminMembersController.php
  src/Controller/SubscriptionController.php
  src/Entity/OgMembership.php
  src/Form/GroupSubscribeForm.php
  src/GroupTypeManager.php
  src/MembershipManager.php
  src/Og.php
  src/OgAccess.php
  src/OgAccessInterface.php
  src/Plugin/Action/AddSingleOgMembershipRole.php
  src/Plugin/Action/ChangeMultipleOgMembershipRolesBase.php
  src/Plugin/Action/ChangeOgMembershipStateBase.php
  src/Plugin/Action/ChangeSingleOgMembershipRoleBase.php
  src/Plugin/Action/DeleteOgMembership.php
  src/Plugin/Action/RemoveSingleOgMembershipRole.php
  src/Plugin/Action/UnblockOgMembership.php
  src/Plugin/Block/RecentGroupContentBlock.php
  src/Plugin/Condition/GroupType.php
  src/Plugin/Derivative/OgLocalTask.php
  src/Plugin/Field/FieldFormatter/GroupSubscribeFormatter.php
  src/Plugin/Field/FieldType/OgStandardReferenceItem.php
  src/Plugin/Field/FieldWidget/OgComplex.php
  src/Plugin/OgDeleteOrphans/Batch.php
  src/Plugin/Validation/Constraint/ValidOgMembershipReferenceConstraintValidator.php
  tests/src/Functional/GroupSubscribeFormatterTest.php
  tests/src/Functional/GroupTabTest.php
  tests/src/Functional/OgComplexWidgetTest.php
  tests/src/Kernel/Action/ActionTestBase.php
  tests/src/Kernel/Cache/Context/OgRoleCacheContextTest.php
  tests/src/Kernel/Entity/EntityCreateAccessTest.php
  tests/src/Kernel/Entity/GetBundleByBundleTest.php
  tests/src/Kernel/Entity/GetMembershipsTest.php
  tests/src/Kernel/Entity/GetUserGroupsTest.php
  tests/src/Kernel/Entity/GroupMembershipManagerTest.php
  tests/src/Kernel/Entity/OgMembershipTest.php
  tests/src/Kernel/EntityReference/Views/OgStandardReferenceRelationshipTest.php
  tests/src/Traits/OgMembershipCreationTrait.php
  tests/src/Unit/Cache/Context/OgContextCacheContextTestBase.php
  tests/src/Unit/Cache/Context/OgRoleCacheContextTest.php
  tests/src/Unit/CreateMembershipTest.php
  tests/src/Unit/DefaultRoleEventTest.php
  tests/src/Unit/GroupCheckTest.php
  tests/src/Unit/GroupContentOperationPermissionTest.php
  tests/src/Unit/GroupPermissionTest.php
  tests/src/Unit/GroupSubscribeFormatterTest.php
  tests/src/Unit/GroupTypeManagerTest.php
  tests/src/Unit/OgAccessTestBase.php
  tests/src/Unit/OgAdminRoutesControllerTest.php
  tests/src/Unit/OgLocalTaskTest.php
  tests/src/Unit/OgResolvedGroupCollectionTest.php
  tests/src/Unit/OgRoleManagerTest.php
  tests/src/Unit/OgRoleTest.php
  tests/src/Unit/PermissionEventTest.php
  tests/src/Unit/Plugin/OgGroupResolver/OgGroupResolverTestBase.php
  tests/src/Unit/Plugin/OgGroupResolver/OgRouteGroupResolverTestBase.php
  tests/src/Unit/SubscriptionControllerTest.php
Labels: Clean-up, Drupal 8, Good first issue, Ready for review

#702 Use instances of interface for variable definitions.
  src/OgMembershipInterface.php
Labels: Clean-up, Documentation, Drupal 8

#716 Fix typos
  src/Form/GroupSubscribeForm.php
  tests/src/Unit/OgAdminRoutesControllerTest.php
Labels: Clean-up, Drupal 8, Ready for review
