Repository Gizra/og, pull requests merged in 2021-09, with the labels that each got.

#721 581 Remove the match_limit schema
  config/schema/og.schema.yml
Labels: Ready for review, Clean-up

#599 Fix delete membership link in og_ui_edit_membership
  og_ui/og_ui.admin.inc
Labels: Bug, Ready for review, Drupal 7

#709 Fix error when resolving the entity on entity.node.revision route
  src/OgRouteGroupResolverBase.php
  tests/modules/og_test/og_test.module
  tests/src/Functional/OgMembershipStateCacheContextTest.php
  tests/src/Unit/Plugin/OgGroupResolver/OgRouteGroupResolverTestBase.php
Labels: Drupal 8, Ready for review, Drupal 9

#701 Add 'auto_add_group_owner_membership' setting
  config/install/og.settings.yml
  config/optional/views.view.og_members_overview.yml
  config/schema/og.schema.yml
  og.install
  og.module
  og_ui/src/Form/AdminSettingsForm.php
  tests/src/Kernel/Action/ActionTestBase.php
  tests/src/Kernel/GroupManagerSubscriptionTest.php
Labels: Drupal 8
